image: adrasteondev/godot-ci:mono-4.2.1

#image: barichello/godot-ci:mono-4.2.1 outdated

# Cache imported assets between runs
cache:
  key: import-assets
  paths:
    - .godot/imported/

stages:
  - import-assets
  - export
  - tests

variables:
  EXPORT_NAME: Bombino

# Open the editor to import assets in case the cache was empty or outdated
import-assets:
  stage: import-assets
  #  before_script:
  #    - wget https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
  #    - dpkg -i packages-microsoft-prod.deb
  #    - rm packages-microsoft-prod.deb
  #    - apt-get update -qq
  #    - apt-get install -y apt-transport-https
  #    - apt-get update -qq
  #    - apt-get install -y dotnet-sdk-6.0
  script:
    - godot --headless --verbose --editor --quit

tests:
  stage: tests
  script:
    - dotnet --version
    - godot --version
    - apt-get update
    - apt-get install -y git-lfs
    - git lfs install
    - git submodule update --init --recursive
    - wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
    - dpkg -i packages-microsoft-prod.deb
    - apt-get update
    - apt-get install -y apt-transport-https
    - apt-get update
    - apt-get install -y dotnet-sdk-7.0
    - dotnet restore
    - rm -f /etc/apt/sources.list.d/microsoft-prod.list
    - add-apt-repository -n ppa:kisak/kisak-mesa
    - apt-get update
    - apt-get install -y mesa-vulkan-drivers binutils
    - wget https://downloads.tuxfamily.org/godotengine/4.2.1/Godot_v4.2.1-stable_linux.x86_64.zip
    - unzip Godot_v4.2.1-stable_linux.x86_64.zip
    - chmod +x Godot_v4.2.1-stable_linux.x86_64/Godot_v4.2.1-stable_linux.x86_64
    - Godot_v4.2.1-stable_linux.x86_64/Godot_v4.2.1-stable_linux.x86_64 --headless --build-solutions --quit || exit 0
    - xvfb-run Godot_v4.2.1-stable_linux.x86_64/Godot_v4.2.1-stable_linux.x86_64 --audio-driver Dummy --run-tests --quit-on-finish --coverage
linux:
  stage: export
  script:
    - mkdir -v -p build/linux
    - godot --headless --verbose --export-release "Linux/X11" ../build/linux/$EXPORT_NAME.x86_64
    - dotnet --version
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/linux

windows:
  stage: export
  script:
    - mkdir -v -p build/windows
    - godot --headless --verbose --export-release "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/windows

mac:
  stage: export
  script:
    - mkdir -v -p build/mac
    - godot --headless --verbose --export-release "Mac OSX" ../build/mac/$EXPORT_NAME.zip
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/mac
